export default {
  "default.customization.menuLabel": "customization ",
  "default.customization.meterReview.menuLabel": "Correction of working hours",
  "default.customization.meterReview.task": "Correction Task",
  "default.customization.meterReview.taskName": "Correction Task Name",
  "default.customization.meterReview.taskDesc": "describe",
  "default.customization.meterReview.acquisitionCycle": "Collection cycle",
  "default.customization.meterReview.formulaMode": "Calculation method",
  "default.customization.meterReview.average": "Average",
  "default.customization.meterReview.materialId": "product",
  "default.customization.meterReview.validDate": "Validity period",
  "default.customization.meterReview.preCycleType": "previously",
  "default.customization.meterReview.cycleType": "Operating cycle",
  "default.customization.meterReview.postCycleType": "Within days (including the same day)",
  "default.customization.meterReview.content": "content",
  "default.customization.meterReview.monthType.month": "month",
  "default.customization.meterReview.monthType.day": "day",
  "default.customization.meterReview.startDate": "Start date",
  "default.customization.meterReview.startTime": "start time",
  "default.customization.meterReview.when": "each",
  "default.customization.meterReview.month": "month",
  "default.customization.meterReview.week": "week",
  "default.customization.meterReview.day": "day",
  "default.customization.meterReview.lastDay": "At the end of the month",
  "default.customization.meterReview.run": "{unit} occurs once",
  "default.customization.meterReview.cycleTypeItems.once": "Once",
  "default.customization.meterReview.cycleTypeItems.day": "Every day",
  "default.customization.meterReview.cycleTypeItems.week": "weekly",
  "default.customization.meterReview.cycleTypeItems.month": "month",
  "default.customization.meterReview.interval": "Number of intervals",
  "default.customization.meterReview.intervalType.once": "Occurred once",
  "default.customization.meterReview.intervalType.day": "Frequency: Once every {day} days",
  "default.customization.meterReview.intervalType.week": "Frequency: Once every {week} week, date of occurrence: {weekDays}",
  "default.customization.meterReview.intervalType.month": "Month of occurrence: {monthList} Date of occurrence: {dayList}",
  "default.customization.meterReview.validate.name": "Can input Chinese, Japanese, letters, numbers-",
  "default.customization.meterReview.validate.leastOne": "Please select at least one day",
  "default.customization.meterReview.validate.leastOneMaterial": "Select at least one material",
  "default.customization.meterReview.monthly": "monthly",
  "default.customization.meterReview.lastOneDay": "Last Day",
  "default.customization.meterReview.reviewMaterial": "Correcting materials"
}